name: Build Android and iOS Libraries

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android and iOS Libraries
    runs-on: macos-latest
    strategy:
      matrix:
        rust-version: [ nightly ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3
          ndk: 21.4.7075529 # 指定所需的 NDK 版本

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods for iOS dependencies
        run: |
          brew install cocoapods
          pod install --project-directory=ios

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Prepare Rust
        run: |
          cargo install --force cargo-make

      - name: Build sqlite3
        run: |
          cd sqlite
          cargo make

      - name: Build iOS
        run: |
          cargo make build-ios

      - name: Build Android
        run: |
          cargo make build-android